"""Collect Phase-0 triage results into one markdown table and apply the frozen decision rules.

Pre-registration: log/nla-harness/2026-08-27_p0-triage-prereg.md

This applies the rules AS WRITTEN and prints the verdict it computes, including when that verdict
is UNINFORMATIVE. It deliberately does not editorialize: the point of freezing a rule is that the
scoring step cannot be renegotiated once the numbers are visible.

Missing stages are reported as missing rather than skipped silently — a summary that omits a
failed stage reads exactly like a summary of a stage that was never planned.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path

_HERE = Path(__file__).resolve().parent
_PROJ = _HERE.parent.parent
_P0 = _PROJ / "data" / "nla" / "p0"


def _load(p: Path):
    try:
        return json.loads(p.read_text())
    except Exception:
        return None


def p01_section() -> list[str]:
    d = _load(_P0 / "layer_rotation.json")
    if not d:
        return ["## P0.1 — layer rotation", "", "**MISSING** — no `layer_rotation.json`.", ""]
    L = d["layers"]
    inst = d["instrument_layer"]
    out = [
        "## P0.1 — layer rotation of the task direction", "",
        f"*{d['n_pairs']} L0/L1b pairs · final prompt token · layer-index gate "
        f"{d['gate_relative_error']:.1e} (< 1e-4 required)*", "",
        f"**Verdict: {d['verdict']}** — min cos(Δ₂₀, Δ_ℓ) over layers 21–27 is "
        f"**{d['min_rotation_layers_21_27']:.3f}** against a frozen threshold of {d['threshold']}.",
        "",
    ]
    if d["verdict"] == "HARD":
        out.append("Re-using the layer-20 vector across 20–27 is **not licensed**. The "
                   "single-layer limit is a measured constraint, not an assumption.")
    else:
        out.append("Injecting the layer-20 vector across 20–27 **is licensed**; Phase 1a gains a "
                   "depth axis with no retraining.")
    out += ["", f"Most coherent layer: **L{d['argmax_coherence_layer']}** "
            f"(instrument sits at L{inst}).", "",
            "| layer | cos vs Δ₂₀ | coherence (LOO) | rel. magnitude |", "|---|---|---|---|"]
    for r in L:
        mark = " ←" if r["layer"] == inst else ""
        out.append(f"| {r['layer']}{mark} | {r['rotation_vs_l20']:.3f} | "
                   f"{r['coherence_loo']:.3f} | {r['rel_magnitude']:.4f} |")
    out.append("")
    return out


def p02_section() -> list[str]:
    new = _load(_P0 / "p02_allreply" / "steer_stats.json")
    old = _load(_PROJ / "data" / "nla" / "n12" / "steer_stats_sweep.json")
    if not new:
        return ["## P0.2 — is the channel the bottleneck?", "",
                "**MISSING** — no `p02_allreply/steer_stats.json`.", ""]
    out = ["## P0.2 — is the channel the bottleneck?", "",
           "*Same 60 pairs, α = 1.0, `positions=all_reply` against the banked `last_prompt`.*", "",
           "```json", json.dumps(new, indent=1)[:2500], "```", ""]
    if old:
        out += ["<details><summary>banked last_prompt reference</summary>", "",
                "```json", json.dumps(old, indent=1)[:1500], "```", "", "</details>", ""]
    out += ["**Decision rule (frozen).** CHANNEL-LIMITED iff V4 improves by ≥ +0.10 with a CI "
            "excluding zero **and** R_random does not match the gain. Otherwise NOT "
            "CHANNEL-LIMITED, and B4's negative stands as a claim about where a correction can "
            "be written.", ""]
    return out


def p03_section() -> list[str]:
    d = _load(_P0 / "p03" / "cells_scored.json")
    done = sorted(p.name for p in (_P0 / "p03").glob("cell_*.done")) if (_P0 / "p03").exists() else []
    out = ["## P0.3 — is layer 20 a live site?", "",
           f"*{len(done)}/10 cells complete.*", ""]
    if not d:
        out += ["Per-cell scores not yet computed (`cells_scored.json` absent). Cells present:",
                "", "".join(f"- `{n}`\n" for n in done) or "- none\n", ""]
        return out
    out += ["| cell | P@1 | cases |", "|---|---|---|"]
    for k, v in d.items():
        out.append(f"| {k} | {v.get('p_at_1', float('nan')):.2f} | {v.get('cases', '?')} |")
    out += ["", "**Decision rule (frozen).** SITE LIVE iff the [20,20] cell differs from the "
            "unsteered baseline by more than the baseline's own seed-to-seed spread, in the same "
            "direction at both seeds. SITE DEAD iff [20,20] is within seed noise while [20,27] is "
            "not. If [20,27] is *also* within seed noise the curve is flat and P0.3 is "
            "**UNINFORMATIVE** — explicitly not to be read as SITE DEAD.", ""]
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", default=str(_P0 / "P0_SUMMARY.md"))
    args = ap.parse_args()

    lines = ["# Phase-0 triage — results", "",
             "*Auto-generated by `nla/src/p0_summary.py`. Decision rules frozen in "
             "`log/nla-harness/2026-08-27_p0-triage-prereg.md` before any run.*", "",
             "---", ""]
    lines += p01_section() + ["---", ""] + p02_section() + ["---", ""] + p03_section()
    lines += ["---", "",
              "## What Phase 0 licenses", "",
              "| P0.2 | P0.3 | conclusion | next |", "|---|---|---|---|",
              "| channel-limited | site live | the channel was the bottleneck | Phase 1a — "
              "position-allocation; re-run the B4 gate at the better allocation |",
              "| not channel-limited | site dead | single-layer late intervention cannot move "
              "this task | Phase 1b — readout paper with a bounded causal negative |",
              "| channel-limited | site dead | contradictory — diagnose, report neither | — |",
              "| not channel-limited | site live | the site works but belief-shaped writes do "
              "not | strongest support for 'no item-level belief' |", ""]

    p = Path(args.out)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text("\n".join(lines))
    print(f"wrote {p} ({len(lines)} lines)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
